
spring:
  devtools:
    restart:
      enabled: false
  datasource:
#    druid:
        url: jdbc:mysql://47.99.216.57:3306/scs?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

