
spring:
  devtools:
    restart:
      enabled: false
  datasource:
#    druid:
        url: jdbc:mysql://47.105.136.224:3306/scs?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: liuyupeng
        password: wwe030615
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

