# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9001
  connection-timeout: 5000ms
spring:
  # 环境 dev|test|prod
  profiles:
    active: prod #dev
  jpa:
#    properties:
      hibernate:
       ddl-auto: update
      show-sql: true
